ARG BASE=base

FROM ghcr.io/christoffercarlsson/devcontainers/${BASE}:latest

ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

RUN npm install -g --ignore-scripts \
        typescript \
        typescript-language-server \
        @biomejs/biome \
    && corepack enable pnpm \
    && npm cache clean --force

LABEL org.opencontainers.image.source="https://github.com/christoffercarlsson/devcontainers" \
      org.opencontainers.image.authors="Christoffer Carlsson <cc@christoffercarlsson.com>" \
      org.opencontainers.image.description="TypeScript, JavaScript, and Node.js development container" \
      org.opencontainers.image.licenses="Unlicense" \
      org.opencontainers.image.title="typescript"

ENTRYPOINT ["/usr/local/sbin/entrypoint"]
