FROM ghcr.io/christoffercarlsson/devcontainers/base@sha256:29ee107d835dbc87b781111d9766e96b2952b571c00e14a7921520e468f8a5dd AS runtime

RUN npm install -g \
        @biomejs/biome \
        deno \
    && npm cache clean --force

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/containers
