FROM ghcr.io/christoffercarlsson/devcontainers/base@sha256:33b8e5b55bbd29d028339bd4252cf8ed1add25534387510ae7abdad1677eb6f5 AS runtime

RUN npm install -g \
        @biomejs/biome \
        deno \
    && npm cache clean --force

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/containers
