ARG BASE=base

FROM ghcr.io/christoffercarlsson/devcontainers/${BASE}:latest

ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

RUN npm install -g --ignore-scripts \
        typescript \
        typescript-language-server \
        @biomejs/biome \
    && corepack enable pnpm \
    && npm cache clean --force

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/containers
