FROM ghcr.io/christoffercarlsson/devcontainers/base@sha256:5cf012886f38e20a9115fadcd0bc0c50abfeffc4701a175b660c70e7cbd22509 AS runtime

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends rustup \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER dev

RUN rustup toolchain install stable \
    && rustup default stable \
    && rustup component add rust-analyzer rust-src

USER root

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/containers
