FROM ghcr.io/christoffercarlsson/devcontainers/base@sha256:f5219ce03b74e2a52442a86f651ad7afe183d0f0b1fd9761f81c9da730ebacd8 AS runtime

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends rustup \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER dev

RUN rustup toolchain install stable \
    && rustup default stable \
    && rustup component add rust-analyzer rust-src

USER root

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/containers
