FROM ghcr.io/christoffercarlsson/devcontainers/base@sha256:33b8e5b55bbd29d028339bd4252cf8ed1add25534387510ae7abdad1677eb6f5 AS runtime

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends rustup \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER dev

RUN rustup toolchain install stable \
    && rustup default stable \
    && rustup component add rust-analyzer rust-src

USER root

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/containers
