FROM ghcr.io/christoffercarlsson/devcontainers/base@sha256:f5219ce03b74e2a52442a86f651ad7afe183d0f0b1fd9761f81c9da730ebacd8 AS runtime

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        golang \
        gopls \
        golang-mvdan-gofumpt-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/containers
