ARG BASE=c

FROM ghcr.io/christoffercarlsson/devcontainers/${BASE}:latest

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        golang \
        gopls \
        golang-mvdan-gofumpt-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/containers
