ARG BASE=base

FROM ghcr.io/christoffercarlsson/devcontainers/${BASE}:latest

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        golang \
        gopls \
        golang-mvdan-gofumpt-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --chmod=644 --chown=dev:dev configs/nvim.lua /home/dev/.nvim.local

LABEL org.opencontainers.image.source="https://github.com/christoffercarlsson/devcontainers" \
      org.opencontainers.image.authors="Christoffer Carlsson <cc@christoffercarlsson.com>" \
      org.opencontainers.image.description="Go development container" \
      org.opencontainers.image.licenses="Unlicense" \
      org.opencontainers.image.title="go"

ENTRYPOINT ["/usr/local/sbin/entrypoint"]
