ARG BASE=base

FROM ghcr.io/christoffercarlsson/devcontainers/${BASE}:latest

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        clang \
        clang-format \
        clang-tidy \
        clangd \
        cmake \
        lld \
        llvm \
        ninja-build \
        pkgconf \
        valgrind \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

LABEL org.opencontainers.image.source="https://github.com/christoffercarlsson/devcontainers" \
      org.opencontainers.image.authors="Christoffer Carlsson <cc@christoffercarlsson.com>" \
      org.opencontainers.image.description="C development container" \
      org.opencontainers.image.licenses="Unlicense" \
      org.opencontainers.image.title="c"

ENTRYPOINT ["/usr/local/sbin/entrypoint"]
