FROM ghcr.io/christoffercarlsson/devcontainers/base@sha256:33b8e5b55bbd29d028339bd4252cf8ed1add25534387510ae7abdad1677eb6f5 AS runtime

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        clang \
        clang-format \
        clang-tidy \
        clangd \
        cmake \
        lld \
        llvm \
        ninja-build \
        pkgconf \
        valgrind \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/containers
