ARG BASE=debian:trixie-slim

FROM debian:trixie-slim AS neovim-builder

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        gettext \
        git \
        ninja-build

RUN git clone --depth 1 --branch stable \
        https://github.com/neovim/neovim /tmp/neovim \
    && cd /tmp/neovim \
    && make CMAKE_BUILD_TYPE=Release \
    && make CMAKE_INSTALL_PREFIX=/tmp/nvim install

RUN git clone --depth 1 --branch 3.18.2 \
        https://github.com/LuaLS/lua-language-server /tmp/lua-language-server \
    && cd /tmp/lua-language-server \
    && chmod +x ./make.sh \
    && ./make.sh > /dev/null

FROM node:24-slim AS node-builder

RUN npm install -g \
    bash-language-server \
    tombi

FROM rust:1-trixie AS rust-tools-builder

RUN cargo install --root /opt/rust-tools \
    bat \
    eza \
    fd-find \
    git-delta \
    jaq \
    ripgrep \
    rumdl \
    tokei

FROM ${BASE}

ARG LANG=en_US.UTF-8
ARG TZ=Europe/Stockholm
ARG USERNAME=dev
ARG USER_SHELL=/bin/bash

ENV EDITOR=nvim
ENV LANG=${LANG}
ENV LC_ALL=${LANG}
ENV TERM=xterm-256color
ENV TZ=${TZ}
ENV VISUAL=nvim

RUN export DEBIAN_FRONTEND=noninteractive \
    && rm -f /etc/dpkg/dpkg.cfg.d/docker \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        fish \
        fzf \
        git \
        gnupg \
        less \
        locales \
        man-db \
        manpages \
        manpages-dev \
        shellcheck \
        shfmt \
        stow \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN echo "${LANG} UTF-8" > /etc/locale.gen \
    && locale-gen

RUN groupadd --gid 1000 ${USERNAME} \
    && useradd --uid 1000 --gid 1000 --shell ${USER_SHELL} --create-home ${USERNAME} \
    && install -o ${USERNAME} -g ${USERNAME} -d /workspace

COPY --from=neovim-builder /tmp/nvim /opt/nvim
RUN ln -s /opt/nvim/bin/nvim /usr/local/bin/nvim

COPY --from=neovim-builder /tmp/lua-language-server /opt/lua-language-server
COPY --chmod=755 scripts/lua-language-server /usr/local/bin/lua-language-server

COPY --from=node-builder /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=node-builder /usr/local/bin /usr/local/bin
RUN rm /usr/local/bin/yarn \
    /usr/local/bin/yarnpkg \
    /usr/local/bin/docker-entrypoint.sh \
    /usr/local/bin/nodejs

COPY --from=rust-tools-builder /opt/rust-tools/bin/ /usr/local/bin/

USER ${USERNAME}
WORKDIR /home/${USERNAME}

RUN rm .bashrc

RUN git clone https://github.com/christoffercarlsson/dotfiles .dotfiles \
    && cd .dotfiles \
    && stow bash \
    && stow fish \
    && stow git \
    && stow neovim \
    && stow rumdl \
    && stow scripts \
    && stow vim

COPY --chmod=644 --chown=${USERNAME}:${USERNAME} configs/gitconfig .gitconfig.local

WORKDIR /workspace

LABEL org.opencontainers.image.source="https://github.com/christoffercarlsson/devcontainers" \
      org.opencontainers.image.authors="Christoffer Carlsson <cc@christoffercarlsson.com>" \
      org.opencontainers.image.description="Base devcontainer" \
      org.opencontainers.image.licenses="Unlicense" \
      org.opencontainers.image.title="base"

CMD ["sleep", "infinity"]
