name: ci
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: base
            path: src/base
          - name: c
            path: src/c
          - name: go
            path: src/go
          - name: rust
            path: src/rust
          - name: typescript
            path: src/typescript
    uses: docker/github-builder/.github/workflows/build.yml@073833262a23a17675c95c4541ab063b7646756b
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      context: ./${{ matrix.path }}
      file: Containerfile
      meta-images: ghcr.io/${{ github.repository }}/${{ matrix.name }}
      meta-tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=ref,event=branch
        type=sha,prefix=,format=long
        type=sha,prefix=,format=short
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
