name: Build and publish images to GitHub Container Registry
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - name: base
            path: src/base
            base: debian:trixie-slim
          - name: c
            path: src/c
            base: base
          - name: go
            path: src/go
            base: c
          - name: rust
            path: src/rust
            base: base
          - name: typescript
            path: src/typescript
            base: base
    uses: docker/github-builder/.github/workflows/build.yml@073833262a23a17675c95c4541ab063b7646756b
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      context: ./${{ matrix.path }}
      file: Containerfile
      build-args: BASE=${{ matrix.base }}
      meta-images: ghcr.io/${{ github.repository }}/${{ matrix.name }}
      meta-tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=ref,event=branch
        type=sha,prefix=,format=long
        type=sha,prefix=,format=short
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
